### ISSUE TITLE
Add to wally

### ISSUE THREAD

**Issue by returnSync** [ambers-careware/pract#16]
Hey! I think it would be nice if you added this to wally, and also this is very good since I'm using it!

**Comment by ambers-careware** [comment]
Added! Make sure you install the latest version on wally since I had to throw away a few test versions to get things working correctly.

You can find the latest package version via:
`$wally search Pract`
![image](https://user-images.githubusercontent.com/93293456/146311748-9014bcea-c195-4d9f-bfdf-1d32b589b7a9.png)

**Comment by returnSync** [comment]
Thanks!
